---
- name: Run windows powershell script
  hosts: all
  become_method: runas
  tasks:
    - win_shell: C:\Users\Administrator\Desktop\ansible_ps_script.ps1 >> C:\Users\Public\Documents\results.txt
      become: yes
      become_user: Administrator
    
    
